version: 0.2

phases:
  pre_build:
    commands:
      - echo "pre_build"
      - apt-get update;  apt-get install -y java-17-amazon-corretto-jdk
      - update-alternatives --set java /usr/lib/jvm/java-17-amazon-corretto/bin/java
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.${REGION}.amazonaws.com
  build:
    commands:
      - echo "build"
      - bash mvnw clean install -DskipTests=true -s settings.xml
      - bash mvnw jib:build -Ddocker.imageName=${IMAGE} -Ddocker.fromImage=${FROM_IMAGE} -Dbuild.number=${CODEBUILD_BUILD_NUMBER} -s settings.xml
  post_build:
    commands:
      - echo "post_build"
      - printf '[{"name":"app","imageUri":"%s"}]' "${IMAGE}:${CODEBUILD_BUILD_NUMBER}" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
